Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "consistent_comma"

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "consistent_comma"

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: "consistent_comma"

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
