name: Rspec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d hubs"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run database migrations
        env:
          DATABASE_HOST: 127.0.0.1
        run: rake db:migrate

      - name: Fetch data
        run: rake data:fetch

      - name: Migrate data
        run: rake data:migrate

      - name: Run RSpec tests
        run: bundle exec rspec
